<%@ Page Title="" Language="C#" MasterPageFile="~/Main2.Master" AutoEventWireup="true" CodeBehind="delete1.aspx.cs" Inherits="onlineshoppingfinal.delete1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <form id="form1" runat="server">
        <table style="width: 243%">
            <tr>
                <td>
                    <table style="width: 100%; height: 13px">
                        <tr>
                            <td>
                                <table style="width: 100%">
                                    <tr>
                                        <td style="width: 205px">
                                            <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="Medium" Text="Choose Your Option::"></asp:Label>
                                        </td>
                                        <td>
                                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource1" DataTextField="PRODUCTTYPE" DataValueField="PRODUCTTYPE">
                                            </asp:DropDownList>
                                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT DISTINCT * FROM &quot;PRODUCT&quot;"></asp:SqlDataSource>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width: 205px">
                                <asp:Button ID="Button1" runat="server" Text="Enter" Font-Bold="True" Font-Size="Medium" Width="99px" Height="23px" OnClick="Button1_Click1" />
                                        </td>
                                        <td>&nbsp;</td>
                                    </tr>
                                </table>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>
                                &nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                    <br />
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="PRODUCTID" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                       <Columns>
                <asp:TemplateField HeaderText="ProductID">
                    <ItemTemplate>
                        <asp:Label ID="lb1" runat="server" Text='<%#Eval("ProductID") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                     <asp:TemplateField HeaderText="ProductType">
                    <ItemTemplate>
                        <asp:Label ID="lb2" runat="server" Text='<%#Eval("ProductType") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                     <asp:TemplateField HeaderText="Brand">
                    <ItemTemplate>
                        <asp:Label ID="lb3" runat="server" Text='<%#Eval("Brand") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                     <asp:TemplateField HeaderText="Models">
                    <ItemTemplate>
                        <asp:Label ID="lb4" runat="server" Text='<%#Eval("Models") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                     <asp:TemplateField HeaderText="Description">
                    <ItemTemplate>
                        <asp:Label ID="lb5" runat="server" Text='<%#Eval("Description") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                     <asp:TemplateField HeaderText="Price">
                    <ItemTemplate>
                        <asp:Label ID="lb6" runat="server" Text='<%#Eval("Price") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                    <asp:TemplateField HeaderText="Rating">
                    <ItemTemplate>
                        <asp:Label ID="lb7" runat="server" Text='<%#Eval("Rating") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                    <asp:TemplateField HeaderText="Number Of Product">
                    <ItemTemplate>
                        <asp:Label ID="lb8" runat="server" Text='<%#Eval("NOofProduct") %>'></asp:Label>
                    </ItemTemplate>
               </asp:TemplateField>
                <asp:TemplateField HeaderText="Image">
                    <ItemTemplate>
                        <asp:Image ID="img" runat="server" ImageUrl='<%#Eval("Image") %>' Height="100" Width="100"></asp:Image>
                    </ItemTemplate>
               </asp:TemplateField>
            </Columns>
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT DISTINCT * FROM &quot;PRODUCT&quot; WHERE (&quot;PRODUCTTYPE&quot; = :PRODUCTTYPE)" DeleteCommand="DELETE FROM &quot;PRODUCT&quot; WHERE &quot;PRODUCTID&quot; = :PRODUCTID">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="DropDownList1" Name="PRODUCTTYPE" PropertyName="SelectedValue" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                </td>
            </tr>
        </table>
    </form>
</asp:Content>
