<%@ Page Title="" Language="C#" MasterPageFile="~/Main2.Master" AutoEventWireup="true" CodeBehind="motherboard.aspx.cs" Inherits="onlineshoppingfinal.motherboard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    
    <form id="form1" runat="server" style="height: 210px; width: 341px">
        <div>
        <asp:GridView ID="mGridView" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>

            </div>
    </form>
    
</asp:Content>
